### ISSUE TITLE
Trial Balance

### ISSUE THREAD

**Issue by HMStitt** [argosity/stockor#11]
This is not the right word for this.  A Trial balance is like a balance sheet showing all of the accounts in a report form.  You cannot look at this by each account.  I think you are thinking of register.

Also, when you choose an account it does nothing...

**Comment by HMStitt** [comment]
Not sure why this was closed out, I see no change, also it is not a priority, but in the end game either should not be here or be corrected.

**Comment by nathanstitt** [comment]
Code hadn't been deployed :(
