### ISSUE TITLE
!!!  Time Invoicing

### ISSUE THREAD

**Issue by HMStitt** [argosity/stockor#13]
This window is a bit funky.  When I originally pulled up a project nothing came up, which could be that there has not been anything loaded for that project.  But then when I tried to search for a project that I new had some it would not give me search window again. I then looked for a reset...none.  So I went to close the window to reopen it and when I clicked the x on the tab it brought up the search window.  Not sure if this was a delay from earlier request or what but it also did not close the tab.  So I then hit the x again and this time it closed the tab.  I then reopened time invoicing and it opened, but did not focus, I stayed on the focused window.  I still cannot bring up search box again. So I typed in Project1 and hit tab on keyboard, it then loaded the calendar tracking window.

**Comment by nathanstitt** [comment]
I think i've fixed the bugs with this screen, please re-test and let me know how it works
