### ISSUE TITLE
SO

### ISSUE THREAD

**Issue by HMStitt** [argosity/stockor#14]
I ran into the same problem with both of these screens so combining them into one.

Same issue with Customer Field.  Could not get customer to come up or search box until typed two letters and then have to type from beginning.

Cannot add a new row or see any way to add a SKU.   I tried clicking add row button but it did nothing.

On invoicing I tried saving anyway without row or sku.  It spinned and spinner and then went back to screen without giving error or saving blank invoice. ??

**Comment by nathanstitt** [comment]
Selecting SKU and adding rows now works.
