### ISSUE TITLE
Time Invoicing

### ISSUE THREAD

**Issue by HMStitt** [argosity/stockor#17]
Ok, attempted to create an invoice (used project1 with GREENWYMAN), unchecked Feb entries so I would invoice only Jan entries.  It created invoice #122 (does not take me to invoice).  

FIrst:  it popped me back to the screen with all of the entries there and check marked as if I just pulled up the project

Second: When I went into Invoices to look at the invoice (#122) it had created it is a $0 dollar invoice with no entries. 

I tried it again and it did the same thing but a new invoice (#123)

**Comment by nathanstitt** [comment]
Found the bug.  It was loading all entries when it loaded, regardless if they'd already been invoiced, and you can't invoice a line twice.

I've changed the screen to no longer request records until a project is selected, and to only load entries that are un-invoiced.
