### ISSUE TITLE
Payment Terms

### ISSUE THREAD

**Issue by HMStitt** [argosity/stockor#18]
Tried to create payment term, was originally making DUEONRECEIPT  error came back to long, max 10 characters, took it to DUEONRECPT (which is 10) still same error, took it to DUEONRCPT (9), same error, took it to DUERCPT (6), same error.

**Comment by nathanstitt** [comment]
Ok!  So the form was actually creating the record for all the attempt where the code was less than 10 characters.  However it wasn't clearing the error message so it appeared that they didn't work :( 

Now it should clear the errors after each save attempt.
