### ISSUE TITLE
Time Entry Color Coding

### ISSUE THREAD

**Issue by HMStitt** [argosity/stockor#20]
Entered a new time for Project1,  came up green all good.  Entered a time on same day for CRPLMUTIFR which has no color assigned.  Came in brown.   Entered a time on a new day for MUTIDEDENC which also has no color assigned.  Came in pink, then turned CRPLMUTIFR to green.
Then entered time on different day for Project2 which is coded orange.  It came in pink and then CRPLMUTIFR turned to orange and MUTIDEDENC turned to green.    Needs a bit of re-examining.  Good news, totals remained separated and correct at end of week though!

**Comment by nathanstitt** [comment]
Soo... it looks like entries that belonged to a project that did not have the color set were being randomly assigned colors.  Additionally the project listing isn't reloaded until the TimeTracking screen is closed and re-opened.  That means that even after you set the colors on a project it won't take effect on the `TimeTracking` screen.

I'm not sure when the projects list should be reloaded though.  It seems like it'd be pretty inefficient to fetch the list every time the screen is selected.  Do you think it's worthwhile to do so?
