### ISSUE TITLE
Total hours no longer on labor invoice

### ISSUE THREAD

**Issue by HMStitt** [argosity/stockor#25]

**Comment by nathanstitt** [comment]
This has been fixed, neglected to close out the issue.

**Comment by HMStitt** [comment]
It is on the printed version, but I would like it on the windowed version of the invoice so it can be checked prior to making a printed invoice and reviewed if needed at a later date.

**Comment by nathanstitt** [comment]
<img width="420" alt="screen shot 2016-07-19 at 9 47 53 pm" src="https://cloud.githubusercontent.com/assets/79566/16973604/8a92936a-4dfa-11e6-9d1c-a5b375fa3a6f.png">
