### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by HMStitt** [argosity/stockor#4]
When updating logo it takes over the setting page.   It will display correctly when uploaded until it is saved.  Shows fine on invoice.

**Comment by HMStitt** [comment]
Ok, found lots of stuff wrong with this...seems that when you upload the file it enlarges the logo and pushes the update button down into the text below, therefor making it unchangeable.  When I reset it it then took it all away and I had no update button at all (yes I was in edit).  I had to reload the page to get it to work again.  This was tested on Safari, whereas initial issue was tested on Chrome...

**Comment by nathanstitt** [comment]
I've changed the logo to no longer expand over the lower elements.  The update button now displays at the top-right of the image.  Please retest and let me know what you think
