### ISSUE TITLE
Check writing address error

### ISSUE THREAD

**Issue by HMStitt** [argosity/stockor#41]
When printing a check it is not putting the address in correctly.  First it was just the state was missing, but now it does random pieces missing.  You cannot edit the address on the Payment screen as it will not keep it and reverts back to what it thinks it should have.

**Comment by HMStitt** [comment]
> When printing a check it is not putting the address in correctly. First it was just the state was missing, but now it does random pieces missing. You cannot edit the address on the Payment screen as it will not keep it and reverts back to what it thinks it should have.

UPDATE:  I believe this is in the Vendor Maintenance issue,  the Vendor Maintenance is not keeping the State saved and therefor not bringing it into check writing.  

As for editing in the Check Writing, now it will let you edit it and print it but it will not save the edit.  So I can add the state and print the check with it on but it will not save, so not a huge deal, minor bug here.

**Comment by nathanstitt** [comment]
Fixed, it should now save the address properly
