### ISSUE TITLE
CALCULATIONS!!!!!

### ISSUE THREAD

**Issue by HMStitt** [argosity/stockor#5]
On the calendar the weekly calculations are not correct.  It does calculate correctly on invoice, but not on weekly amounts.   Top total appears to be correct but does not refresh correctly.  If you accidentally add an amount and then cancel it will add this into top total and leave it ther until reload.  

Upon reload it will bring back in correct amount in top total no matter what the issue.

**Comment by nathanstitt** [comment]
Think I've fixed this, please retest
