### ISSUE TITLE
Double click to add new entry

### ISSUE THREAD

**Issue by HMStitt** [argosity/stockor#6]
Please please please make this a double click to add new entry in time logging.  I am constantly canceling out time, and I think this plays with the totals

**Comment by nathanstitt** [comment]
I've added a smaller popup menu with an easy to target close btn.  I think this should work much better

<img width="948" alt="screen shot 2016-02-03 at 10 06 46 pm" src="https://cloud.githubusercontent.com/assets/79566/12805599/8d1ac104-cac2-11e5-8cfc-2255d16d9dcc.png">
