### ISSUE TITLE
Customer Projects

### ISSUE THREAD

**Issue by HMStitt** [argosity/stockor#8]
Ok, when I first loaded Cust projects it would only give me one SKU.  Once I opened SKU maintenance then they showed up.  

I clicked save after changes and it remained on screen in edit mode.  So I hit reset, it blanked it out but was still in edit mode.

How do I add new Project?  Figured this out but NOT INTUITIVE....

**Comment by nathanstitt** [comment]
Edit mode is set on a per-screen basis not by which record is loaded.  So once a screen is put in edit mode it'll stay that way as long as it's open or until toggled off.  This is intended to allow a person to mass-edit many records one after another.

Additionally, some user account's won't have edit access though and will be restricted to view-only mode.

I've changed the "Save" button to read "Create" when the record is new, hopefully this will help with the confusion.  Additional suggestions welcomed :grinning:

**Comment by HMStitt** [comment]
OK, intuitively (this has happened several times now)  I hit the edit mode and then click on the create to create a new record...so not sure on this.  I understand that you are trying to keep view and edit different, but this seems a bit awkward to me.  So maybe we can keep the create button greyed out until stuff is entered to create the new record.
